### PR TITLE
Add support to representing multiple log files in a single flow. The …

### PR DESCRIPTION
**Pull request by rymichael-stratoscale**
…files entries will be merged by their timestamp. Each line will be added it's source log name that will be colored differently for different logs. If only one log is passed as parameter, the behavior will remain the same as it was.

### CODE REVIEW

**Comment by rom-stratoscale** [comment]
@rymichael-stratoscale can you explain the use case please.

**Comment by rymichael-stratoscale** [comment]
Yes, it is useful when you need to understand an order of events reflected in several different logs. Without this, normally, you would remember a time of some event you are interested in in some log, and then look for it in other logs. When you have to investigate several logs, it becomes more difficult and time consuming. With this feature, you can open serveral logs simultaneously and see them in an interleaved manner.

**Comment by rymichael-stratoscale** [comment]
@rom-stratoscale So, any objections?

**Comment by rom-stratoscale** [comment]
Merged. cc: @arie-stratoscale

**Pull request closed without merging**
